version: "3.7"
services:

  consul:
    image: gliderlabs/consul-server:latest
    container_name: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "53:53/udp"
      - "8301-8302/udp"
      - "8300-8300/tcp"
    command: "-server -bootstrap"

  registrator:
    image: gliderlabs/registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "-cleanup -resync 30 consul://consul:8500"
    depends_on:
      - consul

  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: kennek234
      POSTGRES_USER: postgres
      POSTGRES_DB: Users
    restart: always

  user:
    image: Users:latest
    container_name: user
    ports:
      - 9090:9090
    depends_on:
      - db
    restart: always
